server:
  port: 8093

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootdb?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true