server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${embedded.mysql.host:localhost}:${embedded.mysql.port:3306}/${embedded.mysql.schema:springbootdb}
    username: ${embedded.mysql.user:root}
    password: ${embedded.mysql.password:test123456}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


